from utils.file_utils import open_txt_file, save_txt_file
from summarisation.paragraphing import generate_paragraphs_from_treated_sentences
from summarisation.gpt_summarisation import gpt3_summariser, prompts


if __name__ == "__main__":
    #  Inputs
    filenames = ["Metric Spaces - Lectures 1 & 2 Oxford Mathematics 2nd Year Student Lecture_Transcript.txt"]
    folder = "audio_conversions/youtube_vids"
    prompts_to_use = ["title", "detailed_summary", "bullet_points"]
    aggregate_paras = True

    for filename in filenames:
        #  I/O file paths
        file_path = "../{}/{}".format(folder, filename)
        output_path = "../{}/summaries/{}_Summary.txt".format(folder, filename.split(".")[0])

        #  Opening the transcript and
        transcript = open_txt_file(file_path)
        list_of_paras = transcript.split("\n\n")

        if aggregate_paras:
            list_of_paras, _ = generate_paragraphs_from_treated_sentences(list_of_paras, False)

        final_summary = "Disclaimer:\n\nThe following text has been generated by Startup Blueprint’s proprietary Speech Recognition and NLP software. We are currently testing a suite of speech recognition and NLP models for audio solutions. This is just a non-commercial trial meant for educational purposes. There may some mistakes. The original link to this summary can be found here:\n\n"
        summary_composition_dict = {key: {} for key in prompts_to_use}

        for i, para in enumerate(list_of_paras):

            for prompt_type in prompts_to_use:
                if prompt_type == "title":
                    summary_composition_dict[prompt_type][i] = gpt3_summariser(para, prompts[prompt_type])[1:-1] if '"' or '"' in gpt3_summariser(para, prompts[prompt_type]) else gpt3_summariser(para, prompts[prompt_type])

                else:
                    summary_composition_dict[prompt_type][i] = gpt3_summariser(para, prompts[prompt_type])

            segment_text_final = "".join([summary_composition_dict[key][i] + "\n\n" for key in summary_composition_dict.keys()])

            final_summary += segment_text_final

        save_txt_file(output_path, final_summary)

        print("Completed: " + filename.split(".")[0])
